<?php

use Illuminate\Database\Seeder;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Karachi",
//                "full_name" => NULL,
//                "code" => 'khi',
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Lahore",
//                "full_name" => NULL,
//                "code" => 'lhr',
//
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Faisalabad",
//                "full_name" => NULL,
//                "code" => 'fsd',
//            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Serai",
                "full_name" => NULL,
                "code" => 'sri',
            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Rawalpindi",
//                "full_name" => NULL,
//                "code" => 'rwp',
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Multan",
//                "full_name" => NULL,
//                "code" => 'mul',
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Gujranwala",
//                "full_name" => NULL,
//                "code" => 'gjw',
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Hyderabad City",
//                "full_name" => NULL,
//                "code" => 'hyd',
//            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Peshawar",
//                "full_name" => NULL,
//                "code" => 'pes',
//            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Abbottabad",
                "full_name" => NULL,
                "code" => 'abt',
            ),
//            array(
//                "country_id" => 92,
//                "division_id" => NULL,
//                "name" => "Islamabad",
//                "full_name" => NULL,
//                "code" => 'isb',
//            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Quetta",
                "full_name" => NULL,
                "code" => 'que',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bannu",
                "full_name" => NULL,
                "code" => 'ban',

            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bahawalpur",
                "full_name" => NULL,
                "code" => 'bwn',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sargodha",
                "full_name" => NULL,
                "code" => 'srg',

            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sialkot City",
                "full_name" => NULL,
                "code" => 'slk',

            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sukkur",
                "full_name" => NULL,
                "code" => 'suk',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Larkana",
                "full_name" => NULL,
                "code" => 'lar',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sheikhupura",
                "full_name" => NULL,
                "code" => 'skp',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mibrpur Khas",
                "full_name" => NULL,
                "code" => 'mir',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Rahim yar Khan",
                "full_name" => NULL,
                "code" => 'ryk',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kohat",
                "full_name" => NULL,
                "code" => 'kt',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Jhang Sadr",
                "full_name" => NULL,
                "code" => 'jhs',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Gujrat",
                "full_name" => NULL,
                "code" => 'guj',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bardar",
                "full_name" => NULL,
                "code" => 'br',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kasur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dera Ghazi Khan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Masibwala",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Nawabshah",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Okara",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Gilgit",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Chiniot",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sadiqabad",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Turbat",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dera Ismaibl Khan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Chaman",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Zhob",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mehra",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Parachinar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Gwadar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kundian",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Shahdad Kot",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Haribpur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Matiari",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dera Allahyar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Lodhran",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Batgram",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Thatta",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bagh",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Badibn",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mansehra",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Ziarat",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Muzaffargarh",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Tando Allahyar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dera Murad Jamali",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Karak",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mardan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Uthal",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Nankana Sahib",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Barkhan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Hafizabad",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kotli",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Loralai",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dera Bugti",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Jhang City",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sahiwal",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sanghar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Pakpattan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Chakwal",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Khushab",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Ghotki",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kohlu",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Khuzdar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Awaran",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Nowshera",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Charsadda",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Qila Abdullah",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bahawalnagar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dadu",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Alibabad",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Lakki Marwat",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Chilas",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Pishin",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Tank",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Chitral",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Qila Saifullah",
                "full_name" => NULL,
                "code" => 'qs',
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Shikarpur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Panjgur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mastung",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kalat",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Gandava",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Khanewal",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Narowal",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Khairpur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Malakand",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Vihari",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Saidu Sharif",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Jhelum",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mandi Bahauddibn",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Bhakkar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Toba Tek Singh",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Jamshoro",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kharan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Umarkot",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Hangu",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Timargara",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Gakuch",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Jacobabad",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Alpurai",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Mianwali",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Musa Khel Bazar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Naushahro Fibroz",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "New Mibrpur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Daggar",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Eidgah",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Sibi",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dalbandibn",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Rajanpur",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Leiah",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Upper Dir",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Tando Muhammad Khan",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Attock City",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Rawala Kot",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Swabi",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Kandhkot",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Dasu",
                "full_name" => NULL,
            ),
            array(
                "country_id" => 92,
                "division_id" => NULL,
                "name" => "Athmuqam",
                "full_name" => NULL,
            )
        ];
        $citiesArray = [];
        foreach ($cities as $index => $city){
            $city['id'] = $index + 3758;
            $city['code'] = substr($city['name'],0,3);
            $city['name'] = ucfirst($city['name']);
            $citiesArray[] = $city;
        }
        \DB::table('world_cities')->insert($citiesArray);




    }
}
